# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    secret_key_base: 09999b86c78b83242a5c83ebc481eb7b51f2f28be59df2d4d10b292d15ca204f6db210500784f572a10cb00585c4cbe7018faef1077d3eea7f7a8f1372b45fe0
    s3_secret_key: <%= ENV['S3_SECRET_KEY'] %>
    s3_access_key: <%= ENV['S3_ACCESS_KEY'] %>

test:
    secret_key_base: 340a322777eef78cb16f8d7010995156b6f0d53d98ecdcc9c554b594eaccdce29efb81fdfd8e53a1cdf4d6cc5704408d704adee1fd9f818c809741720a300863
    s3_secret_key: <%= ENV['S3_SECRET_KEY'] %>
    s3_access_key: <%= ENV['S3_ACCESS_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    s3_secret_key: <%= ENV['S3_SECRET_KEY'] %>
    s3_access_key: <%= ENV['S3_ACCESS_KEY'] %>